"""add json terms to channels

Revision ID: 541434fcadf7
Revises: 8cbf46007ddf
Create Date: 2026-03-30 12:15:29.909341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541434fcadf7'
down_revision: Union[str, Sequence[str], None] = '8cbf46007ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('allowed_terms', sa.JSON(), nullable=True))
    op.add_column('channels', sa.Column('blocked_terms', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'blocked_terms')
    op.drop_column('channels', 'allowed_terms')
    # ### end Alembic commands ###
